Repository BetterTyped/hyper-fetch, pull requests merged in 2023-06, with the labels that each got.

#55 feat: 🎸 Added mocker toggling
  documentation/docs/documentation/02-core/mocker.mdx
  packages/core/__tests__/features/mocker/mocker.base.spec.ts
  packages/core/src/adapter/adapter.bindings.ts
  packages/core/src/mocker/mocker.ts
  packages/core/src/request/request.ts
Labels: size/M

#57 fix: 🐛 Backend adapter fix
  packages/core/__tests__/features/adapter/adapter.server.spec.ts
  packages/core/src/adapter/adapter.bindings.ts
  packages/core/src/adapter/adapter.server.ts
Labels: size/S

#59 Feat/client mocker global set
  documentation/docs/documentation/02-core/mocker.mdx
  packages/core/__tests__/features/mocker/mocker.base.spec.ts
  packages/core/src/adapter/adapter.bindings.ts
  packages/core/src/client/client.ts
Labels: size/M

#60 feat: 🎸 Improved library defaults for the queueKeys
  packages/core/__tests__/features/client/client.utils.spec.ts
  packages/core/__tests__/features/request/request.cloning.spec.ts
  packages/core/__tests__/features/request/request.setters.spec.ts
  packages/core/src/adapter/adapter.bindings.ts
  packages/core/src/client/client.constants.ts
  packages/core/src/client/client.ts
Labels: enhancement, size/L

#56 Feat/schema generator
  documentation/docs/documentation/06-generators/01-overview.mdx
  documentation/docs/documentation/06-generators/_category_.json
  documentation/docs/documentation/06-generators/openapi/01-introduction.mdx
  documentation/docs/documentation/06-generators/openapi/_category_.json
  packages/adapter-axios/README.md
  packages/codegen-openapi/.eslintrc.json
  packages/codegen-openapi/README.md
  packages/codegen-openapi/__tests__/features/utils.spec.ts
  packages/codegen-openapi/__tests__/features/v3/generator.spec.ts
  packages/codegen-openapi/__tests__/features/v3/operations.spec.ts
  packages/codegen-openapi/__tests__/global.d.ts
  packages/codegen-openapi/__tests__/jest.setup.ts
  packages/codegen-openapi/__tests__/schemas/v2/petstore-expanded.json
  packages/codegen-openapi/__tests__/schemas/v3/petstore-expanded.json
  packages/codegen-openapi/__tests__/tsconfig.json
  packages/codegen-openapi/jest.config.ts
  packages/codegen-openapi/package.json
  packages/codegen-openapi/project.json
  packages/codegen-openapi/src/cli/index.ts
  packages/codegen-openapi/src/index.ts
  packages/codegen-openapi/src/openapi/generator.ts
  packages/codegen-openapi/src/openapi/http-methods.enum.ts
  packages/codegen-openapi/src/openapi/index.ts
  packages/codegen-openapi/src/openapi/openapi.types.ts
  packages/codegen-openapi/src/openapi/operations.ts
  packages/codegen-openapi/src/openapi/utils.ts
  packages/codegen-openapi/tsconfig.json
  packages/codegen-openapi/yarn.lock
  scripts/build.js
  yarn.lock
Labels: size/XXL
